import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*************  ✨ Windsurf Command ⭐  *************/
/**
 * The root layout of the Next.js app.
 *
 * This layout is common to all pages of the app and sets up the basic
 * structure of the HTML document.
 *
 * @param children - The content of the page.
 * @returns The root layout of the app.
 */
/*******  10059cea-299d-4dc3-9ae3-a21584da7533  *******/export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}